GREETINGS = ["Hello", "Hi", "Hey", "Greetings", "Salutations", "Howdy", "Hola", "Bonjour", "Ciao",
                  "Namaste", "Konnichiwa", "Guten Tag", "Olá", "Shalom", "Salaam", "Zdravstvuyte", "Aloha",
                  "Kia ora", "Hallo", "Hei", "Ahoj", "Hoi", "Sveiki", "Szia", "Merhaba", "Salut", "Hej"]

TRIGGERS_BOT_NAME = ["Legum", "legum", "bot", "Bot", "LEGUM", "BOT", "LEGUMBOT", "LegumBot", "legumbot", "automate", "robot"]

MESSAGES_ANTOINE = [
    "Antoine, tu illumines ma journée rien qu'avec ton sourire.",
    "Coucou Antoine, tu es tout simplement incroyable !",
    "Antoine, tu rends le monde plus beau juste en y étant.",
    "Chaque instant avec toi, Antoine, est un vrai bonheur.",
    "Antoine, tu as le don de rendre tout plus agréable.",
    "Ton rire, Antoine, c'est comme une douce mélodie.",
    "Antoine, tu es la définition même de la gentillesse.",
    "Passer du temps avec toi, Antoine, c'est toujours magique.",
    "Antoine, tu es unique, ne l'oublie jamais !",
    "Chaque moment passé à tes côtés, Antoine, est un trésor.",
    "Antoine, tu es mon petit rayon de soleil.",
    "Antoine, avec toi, même les jours de pluie sont plus lumineux.",
    "Ton sourire, Antoine, c'est de la pure magie.",
    "Antoine, tu es tellement spécial pour moi.",
    "Antoine, chaque minute avec toi est une bénédiction.",
    "Tu es une personne si douce, Antoine, merci d'être toi.",
    "Antoine, tu es la gentillesse incarnée.",
    "Antoine, tu es une source infinie de bonheur.",
    "Avec toi, Antoine, la vie est beaucoup plus belle.",
    "Antoine, ta présence réchauffe toujours mon cœur.",
    "Antoine, tu es une vraie perle rare.",
    "Antoine, tu as ce quelque chose qui rend tout plus joli.",
    "Tu es tout simplement formidable, Antoine.",
    "Antoine, ta gentillesse me touche chaque jour.",
    "Antoine, tu es une vraie bouffée d'air frais.",
    "Ton cœur, Antoine, est aussi grand que l'univers.",
    "Antoine, tu as ce don de toujours me faire sourire.",
    "Antoine, ta douceur est une véritable bénédiction.",
    "Antoine, merci d'être cette personne merveilleuse.",
    "Antoine, tu es l'incarnation même de la bienveillance.",
    "Chaque jour avec toi est une nouvelle aventure, Antoine.",
    "Antoine, tu es un véritable trésor.",
    "Antoine, tu fais briller mes journées de mille couleurs.",
    "Tu es quelqu'un de précieux, Antoine.",
    "Antoine, tu rends ma vie tellement plus joyeuse.",
    "Antoine, tu es la personne qui fait battre mon cœur plus fort.",
    "Antoine, tu es une étoile qui brille même dans la nuit.",
    "Ton sourire, Antoine, est mon remède à tous les maux.",
    "Antoine, tu es une merveille dans ce monde.",
    "Antoine, avec toi, tout semble plus facile.",
    "Antoine, tu es une belle âme, n'en doute jamais.",
    "Antoine, tu es un rayon de soleil dans ma vie.",
    "Antoine, chaque moment passé avec toi est magique.",
    "Antoine, ta gentillesse me fait fondre.",
    "Antoine, tu as un cœur d'or.",
    "Antoine, tu es une personne tellement précieuse.",
    "Antoine, tu es mon petit bonheur quotidien.",
    "Antoine, tu es la raison pour laquelle je souris chaque jour.",
    "Antoine, ta douceur est incomparable.",
    "Antoine, tu es un véritable trésor caché.",
    "Antoine, ta présence suffit à rendre ma journée meilleure.",
    "Antoine, tu es la lumière dans mes jours sombres.",
    "Antoine, avec toi, tout semble plus beau.",
    "Antoine, tu es un ange envoyé sur Terre.",
    "Antoine, tu es tout simplement parfait.",
    "Antoine, tu es la cerise sur le gâteau de ma vie.",
    "Antoine, tu rends tout plus joyeux autour de toi.",
    "Antoine, tu es un rayon de soleil qui réchauffe les cœurs.",
    "Antoine, chaque mot de toi est une douce mélodie à mes oreilles.",
    "Antoine, tu es la plus belle des surprises de ma vie.",
    "Antoine, tu es une bénédiction chaque jour.",
    "Antoine, ton sourire illumine même les jours les plus sombres.",
    "Antoine, tu es une belle personne à l'intérieur comme à l'extérieur.",
    "Antoine, tu fais de ce monde un endroit meilleur.",
    "Antoine, tu es tout ce que je pouvais espérer.",
    "Antoine, tu es la personne la plus douce que je connaisse.",
    "Antoine, tu as un cœur en or.",
    "Antoine, ta présence est un cadeau que je chéris.",
    "Antoine, tu es la raison pour laquelle je crois encore à la magie.",
    "Antoine, tu rends mes jours meilleurs simplement par ta présence.",
    "Antoine, tu es une perle rare dans cet océan d'âmes.",
    "Antoine, tu es le sourire dans ma vie.",
    "Antoine, tu es tout ce qui compte pour moi.",
    "Antoine, tu es un rêve devenu réalité.",
    "Antoine, tu es le plus beau des cadeaux.",
    "Antoine, tu apportes tellement de joie autour de toi.",
    "Antoine, ta tendresse me touche profondément.",
    "Antoine, tu es une source de bonheur inépuisable.",
    "Antoine, tu es plus précieux que tous les trésors du monde.",
    "Antoine, avec toi, je me sens complet(e).",
    "Antoine, tu es une bénédiction que je remercie chaque jour.",
    "Antoine, tu as un cœur tellement pur.",
    "Antoine, ta bienveillance est une source d'inspiration.",
    "Antoine, tu es un vrai cadeau du ciel.",
    "Antoine, ta présence embellit chaque moment.",
    "Antoine, tu es une étoile dans mon ciel.",
    "Antoine, tu fais briller mes journées.",
    "Antoine, tu es un poème à toi tout seul.",
    "Antoine, tu es tout simplement magnifique.",
    "Antoine, tu es la douceur incarnée.",
    "Antoine, tu fais partie des belles choses de ce monde.",
    "Antoine, tu es une belle lumière dans ma vie.",
    "Antoine, tu es la musique de mon cœur.",
    "Antoine, tu es mon petit bonheur chaque jour.",
    "Antoine, tu apportes tant de douceur autour de toi.",
    "Antoine, tu es mon étoile brillante.",
    "Antoine, tu rends chaque jour meilleur rien qu'en étant toi."
]

MESSAGES_MUTED = [
    "Tu t'es auto-mute, tu veux qu'on en parle ?",
    "Tu es sûr de vouloir rester muet ?",
    "Tu as perdu ta langue ?",
    "Tu as décidé de jouer en solo ?",
    "Tu as perdu ta voix ?",
    "Tu as décidé de faire un break vocal ?",
    "Bah alors on se fait daroned ?",
    "Tu as décidé de jouer les muets ?",
    "Bah alors, on a perdu sa langue ?",
    "Bon, on fait un concours de silence ?",
    "Moooh, on a perdu sa voix ?",
    "C'est quoi ce mode furtif ?",
    "T’as décidé d’économiser tes mots ?",
    "Un mute, c'est un mute d'or ?",
    "On t'entend plus, c'est voulu ou accidentel ?",
    "L’art du silence, tu maîtrises ?",
    "Le bouton mute, ton nouvel ami ?",
    "Pourquoi tu nous prives de ta douce voix ?",
    "On fait une manif silencieuse ou quoi ?",
    "T’as mute pour te concentrer ou t’as juste plus d’arguments ?",
    "C’est l’heure de la méditation silencieuse ?",
    "Le mute, c’est une technique ninja ?",
    "Ah, encore un adepte du mute sauvage ?",
    "Mute activé, mais t’es où en fait ?",
    "Toujours là, mais plus de voix ?",
    "Silence radio, tu prépares une surprise ?",
    "T’as décidé de parler avec des gestes ?",
    "Oh, le micro est tombé en panne ?",
    "T’as été envahi par des mimes ?",
    "Micro coupé, mais cerveau toujours en marche j'espère ?",
    "Trop de bruit autour ou t’as juste cliqué sans faire exprès ?",
    "Le bouton mute est devenu ton meilleur pote ?",
    "Ah, on fait dans l’élégance silencieuse maintenant ?",
    "C’est quoi, tu veux passer incognito ?",
    "Un bug ou t’as plus rien à dire ?",
    "Le roi du silence, c’est toi ?",
    "Toujours mute, mais au moins, t’es toujours là ?",
    "Micro off, mystère on ?",
    "Dis-nous, t’as avalé ta langue ?",
    "Le mute, ça te réussit bien !",
    "T’as muté ton cerveau avec ou juste le micro ?",
    "Fais gaffe, trop de silence, on pourrait s’habituer !",
    "Le silence, c’est ton nouveau mode d’expression ?",
    "T’as décidé de parler avec les yeux maintenant ?",
    "T’as rejoint le clan des silencieux ?",
    "T’es mute ou t’es devenu un mime ?",
    "T’as décidé de participer à une minute de silence pour la science ?",
    "T’as plus d’oxygène ou plus de micro ?",
    "On te cherche, mais t’es passé en mode mute ?",
    "Tu prépares un coup d’éclat silencieux ?",
    "Le mute, c’est un superpouvoir chez toi ?",
    "Mute activé, mais la pensée toujours vive ?",
    "C’est l’heure du repos vocal ?",
    "T’as décidé de jouer la carte du mystère ?",
    "Silence, c’est pour le suspense ?",
    "T’as signé un contrat avec le silence ou quoi ?",
    "Tu préfères nous laisser en suspens ?",
    "Le silence, c’est ta nouvelle stratégie ?",
    "Tu veux qu’on t’interviewe par signaux de fumée ?",
    "On a perdu la connexion avec toi ou juste ta voix ?",
    "La voix c’est surfait, c’est ça ?",
    "La discrétion, c’est ton truc maintenant ?",
    "On dirait que tu fais des économies vocales ?",
    "Le mute, c’est un challenge perso ?",
    "Bah alors, on fait grève des cordes vocales ?",
    "T’as mute, mais le mystère reste entier !",
    "T’as choisi de communiquer par télépathie maintenant ?",
    "Le mute, c’est ta nouvelle philosophie de vie ?",
    "Ah, la technique du mutisme discret ?",
    "On t’a perdu ou t’as juste plus rien à dire ?",
    "Micro en panne ou envie de calme ?",
    "Le silence, c’est bien, mais on s’inquiète un peu !",
    "C’est ton tour de mute ou c’est un bug ?",
    "T’as choisi de devenir un sage silencieux ?",
    "T’as décidé de nous laisser cogiter ?",
    "Le mode silence est activé, et nous, on est perdus !",
    "C’est le calme avant la tempête ou juste un bug ?",
    "T’es mute, mais tu prépares un coup de génie, non ?",
    "C’est ta nouvelle technique : parler sans bruit ?",
    "Le bouton mute, c’est devenu ta zone de confort ?",
    "On t’entend pas, mais t’es toujours là, non ?",
    "Le grand maître du silence a encore frappé ?",
    "Le mute, c’est temporaire ou permanent chez toi ?",
    "La parole, c’est surfait, hein ?",
    "Tu t’es fait hacker par un mime ?",
    "C’est la journée internationale du silence chez toi ?",
    "Le silence, c’est pour mieux préparer ton retour ?",
    "T’as mute, mais on sait que tu complotes quelque chose !",
    "Le silence, c’est ta nouvelle arme secrète ?",
    "T’as muté en ninja du silence ?",
    "On t’entend plus, c’est volontaire ou technique ?",
    "Le mute, c’est ton mode par défaut maintenant ?",
    "Silence total, on peut s’inquiéter ?",
    "Tu fais grève de la parole ou t’es juste discret ?",
    "Mute activé, cerveau en mode furtif ?",
    "La parole, c’est plus ton délire ?",
    "C’est le grand silence ou tu fais une pause réflexion ?",
    "Le mute est avec toi aujourd’hui ?",
    "Le silence, ça a l’air de bien t’aller !"
]

MESSAGES_TYPING = [
    "Tu écris un roman ?",
    "C'est une thèse que tu rédiges là ?",
    "On attend le prochain tome avec impatience.",
    "T'as pris ton temps, ça doit être profond.",
    "Ça va être publié ou juste envoyé ici ?",
    "Prend ton temps, on a toute la journée.",
    "Je sens que ça va être du lourd... ou pas.",
    "C’est un monologue intérieur ou tu partages vraiment ?",
    "Tu prépares un best-seller ou juste un pavé ?",
    "Ah, le suspense est insoutenable !",
    "On est sur un scénario de film là, non ?",
    "Une rédaction complète ? J'ai hâte de lire ça.",
    "Je sens qu’il y a du travail derrière ce message...",
    "Courage, t’y es presque.",
    "Est-ce qu’il y aura des chapitres ou tout d’un coup ?",
    "Une histoire longue, ou t’as fini bientôt ?",
    "T’as activé le mode « essayiste » ou quoi ?",
    "Ah, tu t’es lancé dans l’écriture créative ?",
    "Tu cherches à battre le record de mots par message ?",
    "Quand est-ce que ça arrive sur nos écrans ? c’est pour bientôt ?",
    "Je peux prendre un café en attendant la fin ?",
    "Je vais me chercher du popcorn, ça risque d’être long.",
    "On est sur un méga spoil, non ?",
    "Le prochain message sera-t-il aussi long ?",
    "Pas de pression, mais on s'impatiente juste un peu.",
    "Tu veux qu’on t’aide à finir ce message monumental ?",
    "On a hâte de voir le chef-d’œuvre en entier.",
    "Tu fais de la calligraphie numérique ou quoi ?",
    "Je vais te laisser un peu d’espace pour t’exprimer.",
    "Là, c’est du travail d’artiste, ça se voit.",
    "L’inspiration, ça ne se presse pas, on te comprend.",
    "On prépare un débat ou juste un poème épique ?",
    "C'est un jeu de rôle textuel que tu lances là ?",
    "Hésite pas à faire court, hein.",
    "Je m'attends à des citations philosophiques à ce niveau-là.",
    "Le suspense est insoutenable… ou alors c'est juste long.",
    "Si c'est un manifeste, je vote déjà pour.",
    "Tu rédiges une lettre de motivation là ?",
    "N'oublie pas de relire avant d’envoyer, vu l’effort !",
    "On est sur un discours présidentiel, c’est ça ?",
    "Je sens que tu as beaucoup à dire… vraiment beaucoup.",
    "Pas de souci, prends ton temps pour finir ton œuvre.",
    "C’est un message ou une nouvelle que t’écris là ?",
    "On attend la version audio pour les plus pressés.",
    "Waouh, c’est un projet en plusieurs parties, non ?",
    "Encore un peu et tu nous fais une saga.",
    "Tu veux un éditeur ou ça ira ?",
    "C’est moi ou ça prend plus de temps que prévu ?",
    "Ah, c’est pour la postérité tout ça.",
    "Ça a l’air sérieux… ou long, au choix.",
    "Si c’est pour nous impressionner, c’est réussi.",
    "T’as trouvé l’inspiration, ça se voit.",
    "Prends ton temps, t’as l’air d’avoir beaucoup à dire.",
    "Je vais faire une petite sieste en attendant.",
    "La plume est plus forte que l’épée… mais là, c’est long.",
    "T’as besoin d’un rédacteur fantôme pour t’aider ?",
    "C’est un peu long là, mais je suis sûr que ça vaut le coup.",
    "Je me demande si ça va être aussi intense que long.",
    "N’hésite pas à aller droit au but, si tu veux.",
    "Tu nous fais un poème épique, là, c’est sûr.",
    "J’espère qu’il y aura une version TL;DR à la fin.",
    "Tu penses finir ce message avant l’année prochaine ?",
    "Ça devient une saga textuelle à ce stade.",
    "Je me demande s'il y a des chapitres dans ton message.",
    "Un peu long mais on sent que c’est réfléchi.",
    "Tu prépares une encyclopédie ou quoi ?",
    "C’est quoi, tu viens de taper un essai ?",
    "On dirait un message qui va changer le monde.",
    "Je vais installer une chaise, ça a l'air long.",
    "Si c’est pour nous éblouir, ça marche déjà.",
    "On t’attend pour la fin de la saga textuelle.",
    "T’écris l’extension d’un roman, non ?",
    "Je me demande combien de pages ça va faire.",
    "C’est un chef-d’œuvre que tu mijotes, là ?",
    "On te laisse le temps, ça semble être une œuvre majeure.",
    "Waouh, on sent que t’as des choses à dire.",
    "C’est bientôt fini ou tu vas jusqu’au bout de la nuit ?",
    "T’as activé le mode écrivain de l’année ?",
    "Il reste de la place pour un dernier mot ?",
    "La parole est d’argent, mais là, tu tapes l’or massif.",
    "Si c’est aussi long que ça, ça doit être profond !",
    "On part sur une trilogie ou c’est juste un message unique ?",
    "Ah, la prose, c’est ta nouvelle passion ?",
    "J’espère que ça vaudra l’attente !",
    "T’as trouvé le mot juste, enfin ?",
    "T’as pris ton temps, on attend l’explosion littéraire.",
    "J’espère que c’est pas juste un « salut » qui arrive…",
    "Waouh, le moment de gloire approche ?",
    "Tu t’appliques, ça se voit !",
    "Si c’est aussi bien que long, on va se régaler.",
    "Courage, t’es presque au bout de ton message… enfin, j’espère.",
    "On t’attend pour la punchline… ou pour la fin du pavé.",
    "T’as muté en écrivain ou quoi ?",
    "N’oublie pas la conclusion, ça fait long là.",
    "T’es en train d’écrire l’histoire de ta vie ?"
]

MESSAGES_GOODBYE = [
    "Bonne nuit, dors bien... ou pas, on s'en fiche.",
    "Ah, tu nous quittes déjà ? On survivra, t'inquiète.",
    "Déjà fatigué ? C’était intense, j’imagine.",
    "Bon ben, à la prochaine... si tu trouves le courage de revenir.",
    "C’est ça, fuis... On s'en sortira sans toi.",
    "Tu pars déjà ? C’est pas comme si on comptait sur toi.",
    "Oh, tu te déconnectes ? On est dévastés… vraiment.",
    "Trop d'efforts aujourd'hui ? Va te reposer, tu l'as bien mérité... ou pas.",
    "Bon ben, merci pour ta présence... si on peut appeler ça comme ça.",
    "Bye bye, ne te casse pas une jambe en partant.",
    "Ah, enfin la paix ! Bonne nuit alors.",
    "C’est gentil d’avoir essayé, maintenant repose-toi bien.",
    "Bon, on t’attendra... ou pas, c'est pas comme si c'était important.",
    "Tu t'en vas ? Ah, on sentait bien que t’étais à fond… ou pas.",
    "Trop d'effort pour toi aujourd'hui ? Repose-toi bien.",
    "Enfin parti, on va pouvoir avancer tranquille.",
    "Bonne nuit, champion... on sait que c’était difficile.",
    "Wow, tant d'efforts pour nous quitter... impressionnant.",
    "Tu pars déjà ? Quel engagement, c’est touchant.",
    "Ciao ciao, on essaiera de se remettre de cette perte.",
    "Eh bien, ça va nous manquer… ou peut-être pas.",
    "Encore un qui s'éclipse discrètement... on s'en remettra.",
    "Ah, un départ précipité ? On compatit, vraiment.",
    "Bon, à plus... si jamais t’as envie de revenir, hein.",
    "Enfin un peu de tranquillité, bonne nuit à toi !",
    "Oh, c'est l'heure de partir ? Tant mieux, on va pouvoir respirer.",
    "T’as fait de ton mieux, maintenant va te reposer.",
    "Ah, tu nous quittes ? Dommage… ou pas.",
    "Allez, va recharger tes batteries... si tu en as encore.",
    "Tu nous laisses enfin tranquilles ? Parfait.",
    "Déjà en mode déconnexion ? Quelle endurance.",
    "Bonne nuit, dors bien... On sait que tu en as besoin.",
    "Ouf, on va enfin pouvoir respirer ! Bonne nuit quand même.",
    "Bye, repose-toi bien, tu l'as amplement mérité (ironie incluse).",
    "On survit toujours sans toi, pas d’inquiétude.",
    "Et un départ de plus... On va essayer de gérer.",
    "Allez, bonne nuit... Fais de beaux rêves, ou pas.",
    "Tu t’en vas déjà ? C’était si captivant… ou pas.",
    "Eh bien, on va pas pleurer pour ça.",
    "T’as tenu plus longtemps que prévu, c’est déjà ça.",
    "Merci pour ta participation... si on peut appeler ça comme ça.",
    "On sent que tu as tout donné, maintenant va te coucher.",
    "Bonne nuit, repose-toi, tu l’as bien mérité… enfin je crois.",
    "C’est l’heure pour toi ? On s'en remettra, t'inquiète.",
    "Va te reposer, la journée a dû être rude.",
    "Ah, tu pars ? C’est pas comme si c’était inattendu.",
    "Bonne nuit, et t’inquiète, on fera sans toi.",
    "Ah, tu nous quittes ? C’est pas grave, on s’en remettra vite.",
    "Tu pars ? Eh bien, on ne retiendra pas la leçon.",
    "Bonne nuit ! Repose-toi… on le méritait tous.",
    "Bon ben, adieu... ou à plus tard, on verra.",
    "Enfin parti, on va pouvoir continuer sans interruptions."
]

