GREETINGS = ["Hello", "Hi", "Hey", "Greetings", "Salutations", "Howdy", "Hola", "Bonjour", "Ciao",
                  "Namaste", "Konnichiwa", "Guten Tag", "Olá", "Shalom", "Salaam", "Zdravstvuyte", "Aloha",
                  "Kia ora", "Hallo", "Hei", "Ahoj", "Hoi", "Sveiki", "Szia", "Merhaba", "Salut", "Hej"]

TRIGGERS_BOT_NAME = ["Legum", "legum", "bot", "Bot", "LEGUM", "BOT", "LEGUMBOT", "LegumBot", "legumbot"]

MESSAGES_ANTOINE = [
    "Antoine, tu illumines ma journée rien qu'avec ton sourire.",
    "Coucou Antoine, tu es tout simplement incroyable !",
    "Antoine, tu rends le monde plus beau juste en y étant.",
    "Chaque instant avec toi, Antoine, est un vrai bonheur.",
    "Antoine, tu as le don de rendre tout plus agréable.",
    "Ton rire, Antoine, c'est comme une douce mélodie.",
    "Antoine, tu es la définition même de la gentillesse.",
    "Passer du temps avec toi, Antoine, c'est toujours magique.",
    "Antoine, tu es unique, ne l'oublie jamais !",
    "Chaque moment passé à tes côtés, Antoine, est un trésor.",
    "Antoine, tu es mon petit rayon de soleil.",
    "Antoine, avec toi, même les jours de pluie sont plus lumineux.",
    "Ton sourire, Antoine, c'est de la pure magie.",
    "Antoine, tu es tellement spécial pour moi.",
    "Antoine, chaque minute avec toi est une bénédiction.",
    "Tu es une personne si douce, Antoine, merci d'être toi.",
    "Antoine, tu es la gentillesse incarnée.",
    "Antoine, tu es une source infinie de bonheur.",
    "Avec toi, Antoine, la vie est beaucoup plus belle.",
    "Antoine, ta présence réchauffe toujours mon cœur.",
    "Antoine, tu es une vraie perle rare.",
    "Antoine, tu as ce quelque chose qui rend tout plus joli.",
    "Tu es tout simplement formidable, Antoine.",
    "Antoine, ta gentillesse me touche chaque jour.",
    "Antoine, tu es une vraie bouffée d'air frais.",
    "Ton cœur, Antoine, est aussi grand que l'univers.",
    "Antoine, tu as ce don de toujours me faire sourire.",
    "Antoine, ta douceur est une véritable bénédiction.",
    "Antoine, merci d'être cette personne merveilleuse.",
    "Antoine, tu es l'incarnation même de la bienveillance.",
    "Chaque jour avec toi est une nouvelle aventure, Antoine.",
    "Antoine, tu es un véritable trésor.",
    "Antoine, tu fais briller mes journées de mille couleurs.",
    "Tu es quelqu'un de précieux, Antoine.",
    "Antoine, tu rends ma vie tellement plus joyeuse.",
    "Antoine, tu es la personne qui fait battre mon cœur plus fort.",
    "Antoine, tu es une étoile qui brille même dans la nuit.",
    "Ton sourire, Antoine, est mon remède à tous les maux.",
    "Antoine, tu es une merveille dans ce monde.",
    "Antoine, avec toi, tout semble plus facile.",
    "Antoine, tu es une belle âme, n'en doute jamais.",
    "Antoine, tu es un rayon de soleil dans ma vie.",
    "Antoine, chaque moment passé avec toi est magique.",
    "Antoine, ta gentillesse me fait fondre.",
    "Antoine, tu as un cœur d'or.",
    "Antoine, tu es une personne tellement précieuse.",
    "Antoine, tu es mon petit bonheur quotidien.",
    "Antoine, tu es la raison pour laquelle je souris chaque jour.",
    "Antoine, ta douceur est incomparable.",
    "Antoine, tu es un véritable trésor caché.",
    "Antoine, ta présence suffit à rendre ma journée meilleure.",
    "Antoine, tu es la lumière dans mes jours sombres.",
    "Antoine, avec toi, tout semble plus beau.",
    "Antoine, tu es un ange envoyé sur Terre.",
    "Antoine, tu es tout simplement parfait.",
    "Antoine, tu es la cerise sur le gâteau de ma vie.",
    "Antoine, tu rends tout plus joyeux autour de toi.",
    "Antoine, tu es un rayon de soleil qui réchauffe les cœurs.",
    "Antoine, chaque mot de toi est une douce mélodie à mes oreilles.",
    "Antoine, tu es la plus belle des surprises de ma vie.",
    "Antoine, tu es une bénédiction chaque jour.",
    "Antoine, ton sourire illumine même les jours les plus sombres.",
    "Antoine, tu es une belle personne à l'intérieur comme à l'extérieur.",
    "Antoine, tu fais de ce monde un endroit meilleur.",
    "Antoine, tu es tout ce que je pouvais espérer.",
    "Antoine, tu es la personne la plus douce que je connaisse.",
    "Antoine, tu as un cœur en or.",
    "Antoine, ta présence est un cadeau que je chéris.",
    "Antoine, tu es la raison pour laquelle je crois encore à la magie.",
    "Antoine, tu rends mes jours meilleurs simplement par ta présence.",
    "Antoine, tu es une perle rare dans cet océan d'âmes.",
    "Antoine, tu es le sourire dans ma vie.",
    "Antoine, tu es tout ce qui compte pour moi.",
    "Antoine, tu es un rêve devenu réalité.",
    "Antoine, tu es le plus beau des cadeaux.",
    "Antoine, tu apportes tellement de joie autour de toi.",
    "Antoine, ta tendresse me touche profondément.",
    "Antoine, tu es une source de bonheur inépuisable.",
    "Antoine, tu es plus précieux que tous les trésors du monde.",
    "Antoine, avec toi, je me sens complet(e).",
    "Antoine, tu es une bénédiction que je remercie chaque jour.",
    "Antoine, tu as un cœur tellement pur.",
    "Antoine, ta bienveillance est une source d'inspiration.",
    "Antoine, tu es un vrai cadeau du ciel.",
    "Antoine, ta présence embellit chaque moment.",
    "Antoine, tu es une étoile dans mon ciel.",
    "Antoine, tu fais briller mes journées.",
    "Antoine, tu es un poème à toi tout seul.",
    "Antoine, tu es tout simplement magnifique.",
    "Antoine, tu es la douceur incarnée.",
    "Antoine, tu fais partie des belles choses de ce monde.",
    "Antoine, tu es une belle lumière dans ma vie.",
    "Antoine, tu es la musique de mon cœur.",
    "Antoine, tu es mon petit bonheur chaque jour.",
    "Antoine, tu apportes tant de douceur autour de toi.",
    "Antoine, tu es mon étoile brillante.",
    "Antoine, tu rends chaque jour meilleur rien qu'en étant toi."
]
